(function(){
  'use strict';
  if(typeof document==='undefined'||!window.StockScanner||!window.StockScannerAdvanced)return;
  var Scanner=window.StockScanner,Advanced=window.StockScannerAdvanced,KEY='stockscanner.advanced.v2',content=null,state=null,current=null,previous=null;
  function el(id){return document.getElementById(id);}
  function esc(value){return String(value==null?'':value).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function load(){try{return Advanced.state(JSON.parse(localStorage.getItem(KEY)||'{}'));}catch(error){return Advanced.state();}}
  function persist(){localStorage.setItem(KEY,JSON.stringify(state));}
  function locale(){return el('scannerLocale')&&['ko','en','ja'].indexOf(el('scannerLocale').value)>=0?el('scannerLocale').value:'ko';}
  function t(key){var lang=locale();return content&&content.locales[lang]&&content.locales[lang][key]||content&&content.locales.ko[key]||key;}
  function localized(value){return value&&typeof value==='object'?(value[locale()]||value.ko||value.en||''):value;}
  function chosenMethods(){return Array.from(document.querySelectorAll('input[name="advancedMethod"]:checked')).map(function(node){return node.value;});}
  function chosenSecurities(){return Array.from(el('advancedSecurities').selectedOptions).map(function(node){return node.value;});}
  function selectedHorizon(){return el('advancedHorizon').value;}
  function status(message,bad){el('advancedStatus').textContent=message;el('advancedStatus').classList.toggle('counter',!!bad);}
  function download(name,value){var link=document.createElement('a'),blob=new Blob([JSON.stringify(value,null,2)],{type:'application/json'});link.href=URL.createObjectURL(blob);link.download=name;document.body.appendChild(link);link.click();link.remove();setTimeout(function(){URL.revokeObjectURL(link.href);},0);}
  function renderTranslations(){document.querySelectorAll('[data-advanced-key]').forEach(function(node){node.textContent=t(node.getAttribute('data-advanced-key'));});el('advancedBoundary').textContent=t('boundary');}
  function renderSelectors(){
    var securities=Scanner.universe().slice(0,24),selected=state.compareSecurityIds.length>=2?state.compareSecurityIds:securities.slice(0,2).map(function(item){return item.securityId;});
    state.compareSecurityIds=selected;
    el('advancedSecurities').innerHTML=securities.map(function(item){return'<option value="'+esc(item.securityId)+'" '+(selected.indexOf(item.securityId)>=0?'selected':'')+'>'+esc(item.ticker+' · '+item.name)+'</option>';}).join('');
    var defaults=['M-VALUE-001','M-QUALITY-002','M-MOM-001'],methodIds=state.methodIds.length>=3?state.methodIds:defaults;state.methodIds=methodIds;
    el('advancedMethods').innerHTML=Scanner.compatibleMethods('3M').map(function(item){return'<label><input type="checkbox" name="advancedMethod" value="'+esc(item.id)+'" '+(methodIds.indexOf(item.id)>=0?'checked':'')+'><span><b>'+esc(item[locale()]||item.ko)+'</b><small>'+esc(item.family)+'</small></span></label>';}).join('');
    el('advancedGoal').value=state.researchGoal;
    el('advancedAnalytics').checked=state.analyticsEnabled;
  }
  function renderChange(diff){
    var cells=[['changed',diff.changed.length?diff.changed.map(function(item){return item.methodId+' '+(item.delta==null?item.kind:(item.delta>0?'+':'')+item.delta);}).join(' · '):'0'],['unchanged',String(diff.unchanged.length)],['why',diff.reasons.length?diff.reasons.join(' · '):'NO_INPUT_CHANGE'],['unknown',diff.unknown.join(' ')]];
    el('advancedChange').innerHTML=cells.map(function(item){return'<article><h4>'+esc(t(item[0]))+'</h4><p>'+esc(item[1])+'</p></article>';}).join('');
  }
  function renderConflict(value){
    el('advancedConflictVerdict').innerHTML='<b class="'+(value.verdict==='HOLD'?'counter':'positive')+'">'+esc(value.verdict==='HOLD'?t('hold'):value.verdict)+'</b><span> · spread '+value.spread+' · '+esc(value.reasons.join(', ')||'NO_MATERIAL_CONFLICT')+'</span>';
    el('advancedConflict').innerHTML='<table><thead><tr><th>Family</th><th>Direction</th><th>Score</th><th>Counted</th></tr></thead><tbody>'+value.families.map(function(row){return'<tr><th scope="row">'+esc(row.family)+'</th><td>'+esc(row.direction)+'</td><td>'+row.score+'</td><td>1</td></tr>';}).join('')+'</tbody></table><p>'+esc(value.explanation)+'</p>';
  }
  function renderRegimes(rows){el('advancedRegimes').innerHTML=rows.map(function(item){var strong=item.methods.filter(function(row){return row.fit==='STRONG';}).length,weak=item.methods.filter(function(row){return row.fit==='WEAK';}).length;return'<article><h4>'+esc(localized(item.title))+'</h4><p>'+esc(localized(item.summary))+'</p><p><b>STRONG '+strong+'</b> · WEAK '+weak+'</p><details><summary>Method fit</summary><ul>'+item.methods.map(function(row){return'<li><b>'+esc(row.family)+'</b> '+esc(row.fit)+' · '+esc(row.strength)+' / '+esc(row.weakness)+'</li>';}).join('')+'</ul><p>'+esc(item.limitations.join(' '))+'</p></details></article>';}).join('');}
  function renderScenarios(rows){el('advancedScenarios').innerHTML=rows.map(function(item){return'<article><h4>'+esc(localized(item.title))+'</h4><dl><div><dt>Assumptions</dt><dd>'+esc((item.assumptions[locale()]||item.assumptions.ko).join(' · '))+'</dd></div><div><dt>Observe</dt><dd>'+esc((item.observations[locale()]||item.observations.ko).join(' · '))+'</dd></div><div><dt>Change</dt><dd>'+esc((item.changeConditions[locale()]||item.changeConditions.ko).join(' · '))+'</dd></div></dl><p class="muted">numeric probability: —</p></article>';}).join('');}
  function renderEvidence(value){el('advancedEvidenceCoverage').textContent='traceable '+Math.round(value.coverage*100)+'% · claims '+value.claims.length+' · corrections '+value.corrections.length;el('advancedEvidence').innerHTML=value.claims.map(function(claim){var source=claim.sources[0];return'<details><summary>'+esc(claim.methodId+' · '+claim.claim)+'</summary><dl><div><dt>'+esc(t('sourceGrade'))+'</dt><dd>'+esc(source.grade)+'</dd></div><div><dt>'+esc(t('checkedAt'))+'</dt><dd>'+esc(source.checkedAt)+'</dd></div><div><dt>'+esc(t('rights'))+'</dt><dd>'+esc(source.allowedUse)+'</dd></div><div><dt>'+esc(t('calculation'))+'</dt><dd>'+esc(claim.calculation+' · '+source.calculationTrace)+'</dd></div><div><dt>'+esc(t('corrections'))+'</dt><dd>'+esc(source.corrections.length?source.corrections.map(function(x){return x.at+' '+x.reason;}).join(' · '):'0')+'</dd></div></dl></details>';}).join('');}
  function renderTimeline(value){el('advancedTimeline').innerHTML=value.events.length?value.events.slice().reverse().map(function(item){return'<li class="'+(item.kind==='SCORE_SNAPSHOT'?'score-event':'content-event')+'"><time>'+esc(item.at)+'</time><b>'+esc(item.kind)+'</b><span>'+esc(item.summary)+'</span></li>';}).join(''):'<li>'+esc(t('noHistory'))+'</li>';}
  function renderChart(snapshot,diff){
    el('advancedChartSummary').textContent='score '+snapshot.score+' · delta '+(diff.scoreDelta>0?'+':'')+diff.scoreDelta+' · '+snapshot.methods.length+' methods';
    el('advancedBars').innerHTML=snapshot.methods.map(function(row){var width=Math.min(100,Math.max(5,Math.round((row.score+100)/10)*5));return'<div class="research-bar-row"><span>'+esc(row.methodId)+'</span><div class="research-bar-track"><i class="research-width-'+width+'"></i></div><b>'+row.score+'</b></div>';}).join('');
    el('advancedChartTable').innerHTML='<table><thead><tr><th>Method</th><th>Family</th><th>Score</th><th>Change</th></tr></thead><tbody>'+snapshot.methods.map(function(row){var change=diff.changed.concat(diff.unchanged).find(function(item){return item.methodId===row.methodId;});return'<tr><th scope="row">'+esc(row.methodId)+'</th><td>'+esc(row.family)+'</td><td>'+row.score+'</td><td>'+(change&&change.delta!=null?(change.delta>0?'+':'')+change.delta:'—')+'</td></tr>';}).join('')+'</tbody></table>';
  }
  function renderCommodity(){el('advancedCommodity').innerHTML=Advanced.commodity(content).map(function(item){return'<article><span class="preview-pill">'+esc(item.rightsState)+'</span><h4>'+esc(localized(item.title))+'</h4><h5>'+esc(t('facts'))+'</h5><ul>'+item.facts[locale()].map(function(x){return'<li>'+esc(x)+'</li>';}).join('')+'</ul><h5>'+esc(t('interpretation'))+'</h5><ul>'+item.interpretation[locale()].map(function(x){return'<li>'+esc(x)+'</li>';}).join('')+'</ul><p>'+esc(item.impactPath.join(' → '))+'</p><a href="'+esc(item.sourceLink)+'" target="_blank" rel="noopener noreferrer">source ↗</a></article>';}).join('');}
  function renderSavedViews(){el('advancedSavedViews').innerHTML=state.savedViews.map(function(view){return'<li><button type="button" data-advanced-view="'+esc(view.id)+'"><b>'+esc(view.name)+'</b><small>'+view.securityIds.length+' securities · '+view.methodIds.length+' methods</small></button></li>';}).join('')||'<li class="empty">No saved research views.</li>';el('advancedSavedViews').querySelectorAll('[data-advanced-view]').forEach(function(button){button.addEventListener('click',function(){var view=state.savedViews.find(function(item){return item.id===button.getAttribute('data-advanced-view');});if(!view)return;state.compareSecurityIds=view.securityIds.slice();state.methodIds=view.methodIds.slice();state.layout=view.layout;persist();renderSelectors();run();});});}
  function run(){
    try{
      var securityIds=chosenSecurities(),methodIds=chosenMethods();if(securityIds.length<2||securityIds.length>4)throw new Error('SELECT_2_TO_4_SECURITIES');if(methodIds.length<3||methodIds.length>6)throw new Error('SELECT_3_TO_6_METHODS');
      state.compareSecurityIds=securityIds;state.methodIds=methodIds;state.locale=locale();state.researchGoal=el('advancedGoal').value.slice(0,120);persist();
      var asOf=el('advancedAsOf').value||'2026-08-29',baseline='2026-08-01';current=Advanced.createSnapshot(Scanner,{securityId:securityIds[0],methodIds:methodIds,horizon:selectedHorizon(),asOf:asOf,savedAt:new Date().toISOString(),version:'6.0'});previous=state.snapshots.filter(function(item){return item.security.securityId===current.security.securityId;}).slice(-1)[0]||Advanced.createSnapshot(Scanner,{securityId:securityIds[0],methodIds:methodIds,horizon:selectedHorizon(),asOf:baseline,savedAt:baseline+'T00:00:00Z',version:'6.0'});
      var diff=Advanced.diffSnapshots(previous,current);renderChange(diff);renderConflict(Advanced.conflict(current));renderRegimes(Advanced.regimeAnalysis(current,content));renderScenarios(Advanced.scenarios(current,content));renderEvidence(Advanced.evidence(current,content));renderTimeline(Advanced.timeline(state.snapshots.concat([current])));renderChart(current,diff);renderCommodity();renderSavedViews();renderTranslations();status(t('ready'));
    }catch(error){status(t('error')+' '+error.message,true);}
  }
  function wire(){
    el('advancedRun').addEventListener('click',run);
    el('advancedSaveSnapshot').addEventListener('click',function(){if(!current)return;state.snapshots=state.snapshots.filter(function(item){return item.snapshotId!==current.snapshotId;}).concat([current]).slice(-50);persist();renderTimeline(Advanced.timeline(state.snapshots));status('Snapshot saved locally.');});
    el('advancedSaveView').addEventListener('click',function(){var name=prompt('Research view name');if(name==null)return;try{state=Advanced.saveView(state,name,chosenSecurities(),chosenMethods(),state.layout);persist();renderSavedViews();status('Research view saved locally.');}catch(error){status(error.message,true);}});
    el('advancedReset').addEventListener('click',function(){state=Advanced.state();persist();renderSelectors();run();});
    el('advancedExport').addEventListener('click',function(){download('stock-scanner-advanced-research.json',{schemaVersion:'stock-scanner-advanced-backup/v2',boundary:Advanced.BOUNDARY,exportedAt:new Date().toISOString(),state:state});});
    el('advancedImport').addEventListener('change',function(){var file=this.files&&this.files[0];if(!file||file.size>2*1024*1024){status('Choose a backup under 2MB.',true);return;}file.text().then(function(raw){var value=JSON.parse(raw);if(value.schemaVersion!=='stock-scanner-advanced-backup/v2'||value.boundary!==Advanced.BOUNDARY)throw new Error('ADVANCED_BACKUP_INVALID');state=Advanced.state(value.state);persist();renderSelectors();run();}).catch(function(error){status(error.message,true);});});
    el('advancedDelete').addEventListener('click',function(){if(!confirm('Delete all advanced research data from this browser?'))return;localStorage.removeItem(KEY);state=Advanced.state();renderSelectors();run();status('Advanced research data deleted.');});
    el('advancedAnalytics').addEventListener('change',function(){state.analyticsEnabled=this.checked;persist();el('advancedAnalyticsStatus').textContent=this.checked?'Anonymous task events enabled. No personal identifiers are included.':t('analyticsOff');});
    el('advancedIssueForm').addEventListener('submit',function(event){event.preventDefault();try{state=Advanced.issue(state,el('advancedIssueType').value,el('advancedIssueText').value,['advanced-workbench:visible'],content);persist();el('advancedIssueText').value='';el('advancedIssueStatus').textContent='Received locally · status RECEIVED · no personal identifiers requested.';}catch(error){el('advancedIssueStatus').textContent=error.message;}});
    el('scannerLocale').addEventListener('change',function(){state.locale=locale();persist();renderTranslations();run();});
    window.addEventListener('stockscanner-delete-all',function(){localStorage.removeItem(KEY);state=Advanced.state();renderSelectors();run();});
  }
  function focusRequestedResearch(){var key=new URLSearchParams(location.search).get('research'),targets={change:'advancedChangeSection',conflict:'advancedConflictSection',regimes:'advancedRegimesSection',scenarios:'advancedScenariosSection',evidence:'advancedEvidenceSection',timeline:'advancedTimelineSection',commodity:'advancedCommoditySection'};if(!targets[key])return;var target=el(targets[key]);target.setAttribute('tabindex','-1');setTimeout(function(){target.focus({preventScroll:false});},100);}
  function init(payload){content=Advanced.validateContent(payload);state=load();el('advancedAsOf').value='2026-08-29';content.issueTypes.forEach(function(type){el('advancedIssueType').insertAdjacentHTML('beforeend','<option value="'+esc(type)+'">'+esc(type)+'</option>');});renderSelectors();renderTranslations();wire();run();var coverage=Advanced.localeCoverage(content);el('advancedLocaleCoverage').textContent='KO '+coverage.locales.ko.coverage+'% · EN '+coverage.locales.en.coverage+'% · JA core '+(coverage.jaCoreComplete?'100%':'partial');focusRequestedResearch();}
  function start(){fetch('./advanced_research_v2.json',{cache:'no-cache'}).then(function(response){if(!response.ok)throw new Error('ADVANCED_CONTENT_FETCH_FAILED');return response.json();}).then(init).catch(function(error){if(el('advancedStatus'))status('Advanced content unavailable: '+error.message,true);console.error(error);});}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
