(function(){'use strict';
  var loaded=KabuStorage.load(localStorage),state=loaded.data,pendingWorker=null,toastTimer=null;
  document.getElementById('checkMobileUpdate').insertAdjacentElement('afterend',document.getElementById('applyUpdate'));
  var screens=[].slice.call(document.querySelectorAll('[data-screen]')),buttons=[].slice.call(document.querySelectorAll('[data-route]'));
  var labels={};KabuPc.ROUTES.forEach(function(item){labels[item[0]]=item[1];});
  function escapeHtml(value){var d=document.createElement('div');d.textContent=value;return d.innerHTML;}
  function route(name){if(!screens.some(function(x){return x.dataset.screen===name;}))name='today';screens.forEach(function(x){x.hidden=x.dataset.screen!==name;});buttons.forEach(function(x){if(x.dataset.route===name)x.setAttribute('aria-current','page');else x.removeAttribute('aria-current');});history.replaceState(null,'','#'+name);document.title=(labels[name]||'오늘')+' · KABU LENS';document.getElementById('content').focus();}
  buttons.forEach(function(x){x.addEventListener('click',function(){var menu=document.getElementById('mobileMenu');if(menu&&menu.open)menu.close();route(x.dataset.route);});});window.addEventListener('hashchange',function(){route(location.hash.slice(1));});
  function persist(){state=KabuStorage.save(localStorage,state);renderState();}
  function renderState(){['largeText','reduceMotion','highContrast','compactView'].forEach(function(id){var cls=id.replace(/[A-Z]/g,function(x){return '-'+x.toLowerCase();});document.documentElement.classList.toggle(cls,state.settings[id]);document.getElementById(id).checked=state.settings[id];});document.getElementById('watchItems').innerHTML=state.watchlist.length?state.watchlist.map(function(c){return '<li><span>'+c+'</span><button data-remove-watch="'+c+'">삭제</button></li>';}).join(''):'<li>아직 등록한 기업이 없습니다.</li>';document.getElementById('positionItems').innerHTML=state.positions.length?state.positions.map(function(p,i){return '<li><span><b>'+p.code+'</b> '+escapeHtml(p.memo)+'</span><button data-remove-position="'+i+'">삭제</button></li>';}).join(''):'<li>이 기기에 저장한 보유 기록이 없습니다.</li>';renderResearch();}
  function showToast(message,action){var toast=document.getElementById('toast'),button=document.getElementById('toastAction');clearTimeout(toastTimer);document.getElementById('toastText').textContent=message;button.hidden=!action;button.onclick=action?function(){action();toast.hidden=true;}:null;toast.hidden=false;toastTimer=setTimeout(function(){toast.hidden=true;},6000);}
  function currentResearchFilter(){return {query:document.getElementById('companySearch').value,sort:document.getElementById('researchSort').value,direction:document.getElementById('researchDirection').value};}
  function renderResearch(){if(!window.KabuResearch||!document.getElementById('researchResults'))return;var all=KabuResearch.rows(),results=KabuResearch.filterRows(all,currentResearchFilter()),visible=results.slice(0,100),selected=state.compareCodes||[];document.getElementById('researchStatus').textContent='합성 고정자료 '+results.length+'건 중 '+visible.length+'건 표시 · 실제 기업 목록 아님';document.getElementById('researchResults').innerHTML=visible.length?visible.map(function(row){var active=selected.indexOf(row.code)>=0;return '<li class="'+(active?'compare-selected':'')+'"><span class="research-result-main"><b>'+escapeHtml(row.code)+' · '+escapeHtml(row.name)+'</b><small>'+escapeHtml(row.sector)+' · '+escapeHtml(row.evidence)+'</small></span><span class="research-result-actions"><button type="button" data-compare-code="'+row.code+'">'+(active?'비교 해제':'비교 추가')+'</button></span></li>';}).join(''):'<li>일치하는 고정 시험자료가 없습니다.</li>';document.getElementById('savedSearchItems').innerHTML=state.savedSearches.length?state.savedSearches.map(function(item){return '<li><span><b>'+escapeHtml(item.name)+'</b><br><small>'+escapeHtml(item.query||'전체')+' · '+escapeHtml(item.sort)+' · '+escapeHtml(item.direction)+'</small></span><span class="research-result-actions"><button type="button" data-run-search="'+escapeHtml(item.id)+'">적용</button><button type="button" class="secondary" data-remove-search="'+escapeHtml(item.id)+'">삭제</button></span></li>';}).join(''):'<li>저장한 탐색 조건이 없습니다.</li>';var compared=all.filter(function(row){return selected.indexOf(row.code)>=0;});document.getElementById('compareCount').textContent=selected.length+'/4';document.getElementById('compareItems').innerHTML=compared.length?compared.map(function(row){return '<li><span><b>'+escapeHtml(row.code)+' · '+escapeHtml(row.name)+'</b><br><small>'+escapeHtml(row.sector)+' · 가격·추천 없음</small></span><button type="button" data-compare-code="'+row.code+'">제외</button></li>';}).join(''):'<li>비교할 기업을 최대 4개 선택할 수 있습니다.</li>';}
  function loadCatalog(){return fetch('./catalog_10000.json',{cache:'force-cache'}).then(function(response){if(!response.ok)throw new Error('CATALOG_UNAVAILABLE');return response.json();}).then(function(value){if(value.kind!=='SYNTHETIC_FIXED_NOT_REAL_COMPANY')throw new Error('CATALOG_BOUNDARY');var result=KabuResearch.setCatalog(value.rows);if(!result.changed)throw new Error(result.error);renderResearch();}).catch(function(){renderResearch();showToast('1만 건 시험자료를 불러오지 못해 작은 기본 예시를 사용합니다.');});}
  ['companySearch','researchSort','researchDirection'].forEach(function(id){var element=document.getElementById(id);if(element)element.addEventListener(id==='companySearch'?'input':'change',renderResearch);});
  var saveSearchForm=document.getElementById('saveSearchForm');if(saveSearchForm)saveSearchForm.addEventListener('submit',function(e){e.preventDefault();var filter=currentResearchFilter();filter.name=document.getElementById('savedSearchName').value;var saved=KabuResearch.savedSearch(filter);if(!saved)return;state.savedSearches.unshift(saved);state.savedSearches=state.savedSearches.slice(0,50);persist();e.target.reset();showToast('탐색 조건을 이 기기에 저장했습니다.');});
  function researchClick(e){var code=e.target.dataset.compareCode,run=e.target.dataset.runSearch,remove=e.target.dataset.removeSearch;if(code){var result=KabuResearch.toggleCompare(state.compareCodes,code);if(!result.changed&&result.error==='COMPARE_LIMIT'){showToast('비교는 최대 4개까지 가능합니다.');return;}state.compareCodes=result.codes;persist();return;}if(run){var item=state.savedSearches.find(function(value){return value.id===run;});if(!item)return;document.getElementById('companySearch').value=item.query;document.getElementById('researchSort').value=item.sort;document.getElementById('researchDirection').value=item.direction;renderResearch();return;}if(remove){state.savedSearches=state.savedSearches.filter(function(value){return value.id!==remove;});persist();}}
  ['researchResults','savedSearchItems','compareItems'].forEach(function(id){var element=document.getElementById(id);if(element)element.addEventListener('click',researchClick);});
  document.getElementById('watchForm').addEventListener('submit',function(e){e.preventDefault();var code=document.getElementById('watchCode').value.trim().toUpperCase();if(!/^[0-9A-Z]{4,5}$/.test(code))return;if(state.watchlist.indexOf(code)<0)state.watchlist.push(code);persist();e.target.reset();});
  document.getElementById('watchItems').addEventListener('click',function(e){var code=e.target.dataset.removeWatch;if(code){var index=state.watchlist.indexOf(code);state.watchlist.splice(index,1);persist();showToast(code+' 관심 기업을 삭제했습니다.',function(){state.watchlist.splice(index,0,code);persist();showToast('삭제를 되돌렸습니다.');});}});
  document.getElementById('positionForm').addEventListener('submit',function(e){e.preventDefault();var code=document.getElementById('positionCode').value.trim().toUpperCase();if(!/^[0-9A-Z]{4,5}$/.test(code))return;state.positions.push({code:code,memo:document.getElementById('positionMemo').value});persist();e.target.reset();});
  document.getElementById('positionItems').addEventListener('click',function(e){var raw=e.target.dataset.removePosition;if(raw!==undefined){var index=Number(raw),removed=state.positions.splice(index,1)[0];persist();showToast(removed.code+' 보유 기록을 삭제했습니다.',function(){state.positions.splice(index,0,removed);persist();showToast('삭제를 되돌렸습니다.');});}});
  ['largeText','reduceMotion','highContrast','compactView'].forEach(function(id){document.getElementById(id).addEventListener('change',function(e){state.settings[id]=e.target.checked;persist();});});
  var palette=document.getElementById('commandPalette'),commandSearch=document.getElementById('commandSearch');
  function renderCommands(){var matches=KabuPc.filterRoutes(commandSearch.value);document.getElementById('commandItems').innerHTML=matches.map(function(item){return '<button type="button" data-command-route="'+item[0]+'">'+escapeHtml(item[1])+'</button>';}).join('')||'<p>일치하는 화면이 없습니다.</p>';}
  function openCommand(){renderCommands();if(typeof palette.showModal==='function')palette.showModal();else palette.setAttribute('open','');setTimeout(function(){commandSearch.focus();commandSearch.select();},0);}
  document.getElementById('openCommand').addEventListener('click',openCommand);commandSearch.addEventListener('input',renderCommands);document.getElementById('commandItems').addEventListener('click',function(e){var name=e.target.dataset.commandRoute;if(name){palette.close();route(name);}});
  var mobileMenu=document.getElementById('mobileMenu');document.getElementById('openMobileMenu').addEventListener('click',function(){if(typeof mobileMenu.showModal==='function')mobileMenu.showModal();else mobileMenu.setAttribute('open','');});
  var veil=document.getElementById('privacyVeil');function setPrivacy(hidden){veil.hidden=!hidden;document.getElementById('togglePrivacy').textContent=hidden?'화면 가리기 해제':'화면 가리기';if(hidden)document.getElementById('restorePrivacy').focus();}
  document.getElementById('togglePrivacy').addEventListener('click',function(){setPrivacy(veil.hidden);});document.getElementById('restorePrivacy').addEventListener('click',function(){setPrivacy(false);document.getElementById('togglePrivacy').focus();});
  window.addEventListener('keydown',function(e){var action=KabuPc.shortcut(e);if(!action)return;e.preventDefault();if(action.type==='command')openCommand();if(action.type==='privacy')setPrivacy(veil.hidden);if(action.type==='route')route(action.route);});
  function storageAvailable(){try{var key='kabulens.capability';localStorage.setItem(key,'1');localStorage.removeItem(key);return true;}catch(error){return false;}}
  function renderCapabilities(){var values=KabuPc.capabilities({storage:storageAvailable(),worker:'serviceWorker'in navigator,file:'FileReader'in window&&'Blob'in window,dialog:typeof palette.showModal==='function'});document.getElementById('pcStatus').innerHTML=values.map(function(item){return '<div><dt>'+item[0]+'</dt><dd class="'+(item[1]?'ok':'warn')+'">'+(item[1]?'사용 가능':'제한됨')+'</dd></div>';}).join('');}
  var deferredInstall=null;function standalone(){return (window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches)||navigator.standalone===true;}function installSignals(){return {standalone:standalone(),prompt:!!deferredInstall,iosManual:typeof navigator.standalone==='boolean',worker:'serviceWorker'in navigator,controlled:!!(navigator.serviceWorker&&navigator.serviceWorker.controller),waiting:!!pendingWorker};}function renderInstall(){var signals=installSignals(),value=KabuMobile.installState(signals),button=document.getElementById('installApp'),steps=KabuMobile.installSteps(signals),update=KabuMobile.updateState(signals);document.getElementById('mobileInstallStatus').textContent=value.label;document.getElementById('mobileInstallSteps').innerHTML=steps.map(function(step){return '<li>'+escapeHtml(step)+'</li>';}).join('');document.getElementById('mobileUpdateStatus').textContent=update.label;button.hidden=!value.canPrompt;document.getElementById('checkMobileUpdate').disabled=!signals.worker;}
  window.addEventListener('beforeinstallprompt',function(e){e.preventDefault();deferredInstall=e;renderInstall();});window.addEventListener('appinstalled',function(){deferredInstall=null;renderInstall();showToast('홈 화면 앱 설치가 완료됐습니다.');});document.getElementById('installApp').addEventListener('click',function(){if(!deferredInstall)return;deferredInstall.prompt();deferredInstall.userChoice.then(function(){deferredInstall=null;renderInstall();});});
  if(window.visualViewport){var updateViewport=function(){document.documentElement.classList.toggle('mobile-keyboard-open',KabuMobile.keyboardOpen(window.innerHeight,window.visualViewport.height));};window.visualViewport.addEventListener('resize',updateViewport);updateViewport();}
  window.addEventListener('storage',function(e){if(e.key!==KabuStorage.KEY)return;var next=KabuStorage.load(localStorage);if(!next.error){state=next.data;renderState();showToast('다른 탭의 변경을 반영했습니다.');}});
  var SESSION_KEY='kabulens.localSession.v1',sessionToken=sessionStorage.getItem(SESSION_KEY)||'';
  function localApi(path,options){options=options||{};options.headers=Object.assign({'Content-Type':'application/json'},options.headers||{});if(sessionToken)options.headers.Authorization='Bearer '+sessionToken;return fetch(path,options).then(function(response){return response.json().catch(function(){return {message:'서버 응답을 읽지 못했습니다.'};}).then(function(payload){if(!response.ok){var error=new Error(payload.message||payload.error||'요청 실패');error.status=response.status;throw error;}return payload;});});}
  function localAvailable(){return location.protocol!=='file:';}
  var COMMERCIAL_SCOPE={version:'3.0',stage:'STAGE1',liteMonthlyKrw:7900,liteEngines:['E02','E03','E04','E05','E15','E18','E20','E25'],prohibited:['ORDER','AUTO_TRADE','INVESTMENT_RECOMMENDATION','UNLICENSED_REALTIME_QUOTES','UNLICENSED_REDISTRIBUTION']};
  function renderCommercialScope(value){value=value||COMMERCIAL_SCOPE;var lite=value.plans?value.plans.LITE:{monthlyKrw:value.liteMonthlyKrw,engines:value.liteEngines};var status=document.getElementById('commercialScopeStatus'),blocked=document.getElementById('commercialScopeBlocked');if(!status||!blocked)return;status.innerHTML='<div><dt>Free</dt><dd class="ok">저장·내보내기·삭제 유지</dd></div><div><dt>Lite</dt><dd>'+Number(lite.monthlyKrw).toLocaleString('ko-KR')+'원/월 · 엔진 '+lite.engines.length+'개</dd></div><div><dt>출시 엔진</dt><dd>'+lite.engines.map(escapeHtml).join(' · ')+'</dd></div>';blocked.textContent='주문·자동매매·투자추천·무허가 실시간 시세는 제공하지 않습니다.';}
  function loadCommercialScope(){if(!localAvailable()){renderCommercialScope();return;}fetch('/v1/commercial-scope',{cache:'no-store'}).then(function(response){if(!response.ok)throw new Error('SCOPE_UNAVAILABLE');return response.json();}).then(renderCommercialScope).catch(function(){renderCommercialScope();});}
  function loadBillingReadiness(){if(!globalThis.KabuBilling)return;if(!localAvailable()){KabuBilling.render(KabuBilling.STATIC_POLICY);return;}fetch('/v1/billing/policy',{cache:'no-store'}).then(function(response){if(!response.ok)throw new Error('BILLING_UNAVAILABLE');return response.json();}).then(KabuBilling.render).catch(function(){KabuBilling.render(KabuBilling.STATIC_POLICY);});}
  function renderStaticCommercialReadiness(status,blocked){status.innerHTML='<div><dt>PC 상용화도</dt><dd class="warn">90/100 · 외부 증거 대기</dd></div><div><dt>모바일 상용화도</dt><dd class="warn">90/100 · 외부 증거 대기</dd></div><div><dt>상업 운영</dt><dd class="warn">차단</dd></div>';blocked.textContent='공개 정적판은 서버 판정 정보와 분리되어 있습니다. 점수를 올리지 않았으며, 실제 로그인·허가 데이터·실기기·시험 사용자 증거가 필요합니다.';}
  function loadCommercialReadiness(){var status=document.getElementById('commercialGateStatus'),blocked=document.getElementById('commercialGateBlocked');if(!localAvailable()){renderStaticCommercialReadiness(status,blocked);return;}fetch('/v1/commercial-readiness',{cache:'no-store'}).then(function(response){if(!response.ok)throw new Error('READINESS_UNAVAILABLE');return response.json();}).then(function(value){status.innerHTML='<div><dt>PC 상용화도</dt><dd class="'+(value.pc.score===100?'ok':'warn')+'">'+value.pc.score+'/100</dd></div><div><dt>모바일 상용화도</dt><dd class="'+(value.mobile.score===100?'ok':'warn')+'">'+value.mobile.score+'/100</dd></div><div><dt>상업 운영</dt><dd class="'+(value.commercialOperationReady?'ok':'warn')+'">'+(value.commercialOperationReady?'가능':'차단')+'</dd></div>';blocked.textContent=value.blockedGates.length?'남은 실제 증거 '+value.blockedGates.length+'개: '+value.blockedGates.map(function(item){return item.label;}).join(', '):'모든 실제 증거 확인 완료';}).catch(function(){renderStaticCommercialReadiness(status,blocked);});}
  function setSessionUi(active,text){document.getElementById('localAuthStatus').textContent=text;document.getElementById('endLocalSession').hidden=!active;document.getElementById('localAuthForm').hidden=active;}
  function clearSession(message){sessionToken='';sessionStorage.removeItem(SESSION_KEY);setSessionUi(false,message||'세션 없음');document.getElementById('notificationItems').innerHTML='';document.getElementById('notificationStatus').textContent='설정에서 로컬 시험 세션을 시작하세요.';document.getElementById('retentionStatus').textContent='먼저 로컬 시험 세션을 시작하세요.';}
  function checkSession(){if(!localAvailable()){setSessionUi(false,'로컬 API 서버로 열었을 때 사용할 수 있습니다.');return Promise.resolve(false);}if(!sessionToken){clearSession();return Promise.resolve(false);}return localApi('/v1/local-auth/session').then(function(value){setSessionUi(true,'시험 세션 사용 중 · 재시작 보존 · '+value.expiresAt+'까지');return true;}).catch(function(){clearSession('세션이 끝났습니다. 다시 시작하세요.');return false;});}
  function renderNotifications(){if(!sessionToken){document.getElementById('notificationStatus').textContent='먼저 로컬 시험 세션을 시작하세요.';return Promise.resolve();}document.getElementById('notificationStatus').textContent='알림 확인 중';return localApi('/v1/local-notifications').then(function(value){document.getElementById('notificationStatus').textContent='읽지 않은 알림 '+value.unread+'개 · 외부 푸시 OFF';document.getElementById('notificationItems').innerHTML=value.items.length?value.items.map(function(item){return '<li class="notification '+(item.readAt?'read':'unread')+'"><span><b>'+escapeHtml(item.title)+'</b><br>'+escapeHtml(item.body)+'<br><small>'+escapeHtml(item.createdAt)+'</small></span>'+(item.readAt?'':'<button data-read-notification="'+item.id+'">읽음</button>')+'</li>';}).join(''):'<li>알림이 없습니다.</li>';}).catch(function(error){if(error.status===401)clearSession('세션이 끝났습니다. 다시 시작하세요.');else document.getElementById('notificationStatus').textContent=error.message;});}
  function previewRetention(){var status=document.getElementById('retentionStatus');if(!sessionToken){status.textContent='먼저 로컬 시험 세션을 시작하세요.';return Promise.resolve();}status.textContent='보존 영향 계산 중';return localApi('/v1/local-retention/preview').then(function(value){status.textContent='자동 삭제 0건 · 만료/종료 세션 '+value.impact.expiredOrRevokedSessions+'개 · 90일 지난 알림 검토 후보 '+value.impact.notificationReviewCandidates+'개 · 복구: '+value.recovery.method;}).catch(function(error){if(error.status===401)clearSession('세션이 끝났습니다. 다시 시작하세요.');else status.textContent=error.message;});}
  document.getElementById('localAuthForm').addEventListener('submit',function(e){e.preventDefault();if(!localAvailable()){setSessionUi(false,'로컬 API 서버로 열었을 때 사용할 수 있습니다.');return;}var profile=document.getElementById('localProfileId').value.trim();localApi('/v1/local-auth/session',{method:'POST',body:JSON.stringify({profileId:profile}),headers:{Authorization:''}}).then(function(value){sessionToken=value.token;sessionStorage.setItem(SESSION_KEY,sessionToken);setSessionUi(true,'시험 세션 시작됨 · 재시작 보존 · '+value.expiresAt+'까지');e.target.reset();return renderNotifications();}).catch(function(error){setSessionUi(false,error.message);});});
  document.getElementById('endLocalSession').addEventListener('click',function(){localApi('/v1/local-auth/session',{method:'DELETE'}).catch(function(){return null;}).then(function(){clearSession('시험 세션을 종료했습니다.');});});document.getElementById('refreshNotifications').addEventListener('click',renderNotifications);document.getElementById('previewRetention').addEventListener('click',previewRetention);document.getElementById('notificationItems').addEventListener('click',function(e){var id=e.target.dataset.readNotification;if(!id)return;localApi('/v1/local-notifications/read',{method:'POST',body:JSON.stringify({notificationId:id})}).then(renderNotifications).catch(function(error){document.getElementById('notificationStatus').textContent=error.message;});});
  document.getElementById('officialLookup').addEventListener('click',function(){window.open('https://www.jpx.co.jp/listing/stocks/new/index.html','_blank','noopener');});
  function parseCsv(text){if(text.length>2*1024*1024)throw new Error('파일이 2MB를 넘습니다.');if(/^[=+\-@]/m.test(text))throw new Error('수식으로 시작하는 셀이 있어 차단했습니다.');var lines=text.replace(/^\uFEFF/,'').trim().split(/\r?\n/);if(lines.length<2||lines.length>5001)throw new Error('1~5,000행만 사용할 수 있습니다.');var required=['security_code','date','open','high','low','close','volume'],heads=lines[0].split(',').map(function(x){return x.trim();});if(required.some(function(x){return heads.indexOf(x)<0;}))throw new Error('필수 열이 없습니다.');var rows=lines.slice(1,6).map(function(line){var cells=line.split(','),row={};heads.forEach(function(h,i){row[h]=(cells[i]||'').trim();});var o=Number(row.open),h=Number(row.high),l=Number(row.low),c=Number(row.close),v=Number(row.volume);if(!/^[0-9A-Z]{4,5}$/.test(row.security_code)||!/^\d{4}-\d{2}-\d{2}$/.test(row.date)||[o,h,l,c,v].some(function(x){return !Number.isFinite(x)||x<0;})||h<Math.max(o,c,l)||l>Math.min(o,c,h))throw new Error('코드·날짜·OHLC·거래량 형식이 잘못되었습니다.');return row;});return {count:lines.length-1,headers:heads,preview:rows};}
  function clearCsv(){document.getElementById('csvFile').value='';document.getElementById('csvStatus').textContent='선택한 파일 없음';document.getElementById('csvPreview').innerHTML='';}
  document.getElementById('clearImport').addEventListener('click',clearCsv);document.getElementById('csvFile').addEventListener('change',function(e){var file=e.target.files[0];if(!file)return;file.text().then(function(text){var result=parseCsv(text);document.getElementById('csvStatus').textContent=result.count+'행 확인 완료 · 서버에 저장하지 않음';var table='<table><thead><tr>'+result.headers.map(function(h){return '<th>'+escapeHtml(h)+'</th>';}).join('')+'</tr></thead><tbody>'+result.preview.map(function(r){return '<tr>'+result.headers.map(function(h){return '<td>'+escapeHtml(r[h])+'</td>';}).join('')+'</tr>';}).join('')+'</tbody></table>';document.getElementById('csvPreview').innerHTML=table;}).catch(function(err){clearCsv();document.getElementById('csvStatus').textContent=err.message;});});
  document.getElementById('exportData').addEventListener('click',function(){var blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kabulens-user-backup.json';a.click();URL.revokeObjectURL(a.href);document.getElementById('backupStatus').textContent='내보내기 파일을 만들었습니다.';});
  var recoveryButton=document.getElementById('exportRecovery');if(loaded.recovery){recoveryButton.hidden=false;recoveryButton.addEventListener('click',function(){var blob=new Blob([loaded.recovery.raw],{type:'application/octet-stream'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kabulens-corrupt-storage-recovery.txt';a.click();URL.revokeObjectURL(a.href);document.getElementById('backupStatus').textContent='손상 원본 사본을 만들었습니다. 기존 저장값은 바꾸지 않았습니다.';});}
  function researchExportRows(){return window.KabuResearch?KabuResearch.exportRows(state):[];}
  function renderPrintBundle(){var rows=researchExportRows(),host=document.getElementById('printBundleRows');if(!host)return;host.innerHTML=rows.length?rows.map(function(row){return '<tr><td>'+escapeHtml(row.type)+'</td><td>'+escapeHtml(row.value)+'</td><td>'+escapeHtml(row.note)+'</td></tr>';}).join(''):'<tr><td colspan="3">내보낼 자료 없음</td></tr>';}
  document.getElementById('exportResearchCsv').addEventListener('click',function(){var rows=researchExportRows(),blob=new Blob([KabuResearch.toCsv(rows)],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='kabulens-research-bundle.csv';a.click();URL.revokeObjectURL(a.href);document.getElementById('backupStatus').textContent='CSV 조사 묶음 '+rows.length+'행을 만들었습니다.';});
  document.getElementById('printResearch').addEventListener('click',function(){renderPrintBundle();document.body.classList.add('printing-research');window.print();setTimeout(function(){document.body.classList.remove('printing-research');},0);document.getElementById('backupStatus').textContent='인쇄 화면에서 PDF 저장을 선택할 수 있습니다.';});
  document.getElementById('importData').addEventListener('change',function(e){var file=e.target.files[0];if(!file)return;if(file.size>2*1024*1024){e.target.value='';document.getElementById('backupStatus').textContent='2MB 이하 복구 파일만 사용할 수 있습니다. 현재 자료는 그대로입니다.';return;}file.text().then(function(text){state=KabuStorage.restore(localStorage,text);renderState();document.getElementById('backupStatus').textContent='복구 완료';e.target.value='';}).catch(function(){e.target.value='';document.getElementById('backupStatus').textContent='복구 파일을 읽지 못했습니다. 현재 자료는 그대로입니다.';});});
  var migration=document.getElementById('migrationState');migration.textContent=loaded.error?'기존 저장자료를 바꾸지 않고 안전 기본상태로 열었습니다. 손상 원본을 별도 내보낼 수 있습니다.':loaded.migratedFrom?'이전 자료를 새 형식으로 복사했습니다. 원본 키는 유지했습니다.':'저장자료 형식 v6 확인 완료';
  function setConnection(online){document.getElementById('connection').textContent=online?'온라인':'오프라인 · 저장된 화면 사용 중';}
  function connection(){if(!navigator.onLine){setConnection(false);return Promise.resolve(false);}return fetch('./__connectivity__?t='+Date.now(),{method:'HEAD',cache:'no-store'}).then(function(){setConnection(true);return true;}).catch(function(){setConnection(false);return false;});}
  window.addEventListener('online',connection);window.addEventListener('offline',function(){setConnection(false);});connection();
  if('serviceWorker'in navigator&&location.protocol!=='file:'){navigator.serviceWorker.register('./sw.js').then(function(reg){if(reg.waiting)offer(reg.waiting);reg.addEventListener('updatefound',function(){var w=reg.installing;w.addEventListener('statechange',function(){if(w.state==='installed'&&navigator.serviceWorker.controller)offer(w);});});renderInstall();return navigator.serviceWorker.ready;}).then(function(){renderInstall();}).catch(function(){renderInstall();showToast('오프라인 준비를 완료하지 못했습니다. 온라인 기능은 계속 사용할 수 있습니다.');});navigator.serviceWorker.addEventListener('controllerchange',function(){location.reload();});}
  function offer(worker){pendingWorker=worker;document.getElementById('applyUpdate').hidden=false;renderInstall();}document.getElementById('applyUpdate').addEventListener('click',function(){if(pendingWorker)pendingWorker.postMessage({type:'APPLY_UPDATE'});});document.getElementById('checkMobileUpdate').addEventListener('click',function(){var status=document.getElementById('mobileUpdateStatus');if(!('serviceWorker'in navigator)||location.protocol==='file:'){status.textContent=KabuMobile.updateState({worker:false}).label;return;}status.textContent='새 버전 확인 중';navigator.serviceWorker.getRegistration().then(function(reg){if(!reg)throw new Error('NO_REGISTRATION');return reg.update().then(function(){if(reg.waiting)offer(reg.waiting);else{renderInstall();status.textContent='확인 완료 · 적용할 새 버전이 있으면 자동으로 안내합니다.';}});}).catch(function(){status.textContent='새 버전을 확인하지 못했습니다. 현재 버전과 저장자료는 그대로입니다.';});});
  window.addEventListener('error',function(){showToast('화면 처리 중 문제가 생겼습니다. 저장된 자료는 유지됩니다.');});window.addEventListener('unhandledrejection',function(){showToast('요청을 마치지 못했습니다. 연결 상태를 확인해 주세요.');});
  renderState();renderPrintBundle();loadCatalog();renderCapabilities();renderInstall();loadCommercialScope();loadBillingReadiness();loadCommercialReadiness();checkSession().then(function(active){if(active)renderNotifications();});route(location.hash.slice(1)||'today');
})();
