(function(){
  'use strict';
  var stores={},mode='daily',page=0,size=30,rows=[],requestId=0,parity=null;
  function el(id){return document.getElementById(id);}
  function en(){return el('marketLocale').value==='en';}
  function t(ko,english){return en()?english:ko;}
  function esc(v){return String(v==null?'—':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
  function numeric(v){return v==null?'—':Number(v).toLocaleString(en()?'en-US':'ko-KR',{maximumFractionDigits:4});}
  function labels(){document.documentElement.lang=en()?'en':'ko';el('marketTitle').textContent=t('종목을 찾고, 자료 범위를 확인하세요','Find listings. Know the data behind them.');el('marketIntro').textContent=t('대만 일별 시세와 30개국 종목 발견 명부를 제공합니다. 실시간 시세나 상승확률은 제공하지 않습니다.','Taiwan daily prices and a 30-country listing discovery directory. No real-time quotes or probability forecasts.');el('coverageBenchmarkEyebrow').textContent=t('커버리지 기준선','COVERAGE BENCHMARK');el('coverageBenchmarkTitle').textContent=t('Investing.com과 비교하는 시장 범위','Market coverage compared with Investing.com');el('coverageBenchmarkIntro').textContent=t('기업 수와 금융상품 수를 분리해 같은 기준으로 비교합니다. 아래 숫자는 현재 서비스가 모두 커버했다는 뜻이 아닙니다.','Companies and financial instruments are compared separately. These figures do not mean this service covers them all.');el('coverageWfeLabel').textContent=t('WFE 상위 30개 시장 기업 기준선','WFE top-30 market company baseline');el('coverageInvestingLabel').textContent=t('Investing.com 기업 공개 하한','Investing.com public company floor');el('coverageCurrentLabel').textContent=t('현재 발견 후보','Current discovery candidates');el('coverageGapLabel').textContent=t('최소 기업 격차','Minimum company gap');el('coverageMarketsTitle').textContent=t('상위 30개 시장 기준 보기','View top-30 market baseline');el('modeLabel').textContent=t('자료 선택','Dataset');el('queryLabel').textContent=t('종목 코드·회사명 검색','Search code or company');el('countryLabel').textContent=t('국가','Country');el('marketSearch').textContent=t('검색','Search');el('marketPrev').textContent=t('이전','Previous');el('marketNext').textContent=t('다음','Next');el('sourcesTitle').textContent=t('자료 출처·사용 조건·지원 범위','Sources, terms and coverage');el('marketMode').options[0].text=t('대만 일별 시세','Taiwan daily prices');el('marketMode').options[1].text=t('30개국 종목 명부','30-country directory');if(parity)renderParity();}
  function renderParity(){if(!parity)return;var b=parity.benchmarks,w=parity.currentProject,d=parity.derived;el('coverageWfeValue').textContent=numeric(b.wfeTop30.listedCompaniesTotal);el('coverageInvestingValue').textContent=t('> '+numeric(b.investingCom.companyFloor),'> '+numeric(b.investingCom.companyFloor));el('coverageCurrentValue').textContent=numeric(w.globalDiscoveryCandidates);el('coverageGapValue').textContent=t('최소 '+numeric(d.minimumCompanyGapToInvestingFloor), 'at least '+numeric(d.minimumCompanyGapToInvestingFloor));el('coverageBenchmarkBoundary').textContent=t('WFE 기업 기준선 '+numeric(b.wfeTop30.listedCompaniesTotal)+'개와 Investing.com 공개 하한 '+numeric(b.investingCom.companyFloor)+'개 이상은 동일한 완전 일치 데이터셋이 아닙니다. 공식 거래소 상품 마스터와 데이터 권리가 확보되기 전에는 생산 커버리지로 승격하지 않습니다.','The WFE baseline and Investing.com public floor are not identical datasets. This project will not promote them to production coverage until official exchange masters and data rights are secured.');el('coverageMarketsBody').innerHTML='<p>'+esc(t('기준일 '+parity.asOf+' · WFE 국내 상장기업 기준','Reference '+parity.asOf+' · WFE domestic listed-company basis'))+'</p><ol>'+parity.markets.map(function(m){return'<li>'+esc(m.unit)+' · '+esc(m.countryCode)+' · '+numeric(m.listedCompanies)+'개</li>';}).join('')+'</ol><p><a href="'+esc(b.wfeTop30.sourceUrl)+'" target="_blank" rel="noopener noreferrer">WFE 원자료 ↗</a> · <a href="'+esc(b.investingCom.sourceUrl)+'" target="_blank" rel="noopener noreferrer">Investing.com 공개 범위 ↗</a></p>';}
  function detail(row){
    var daily=mode==='daily',data=stores[mode];
    var facts=daily?[[t('기준 거래일','Trading date'),row.asOf],[t('종가','Close'),numeric(row.close)+' TWD'],[t('시가','Open'),numeric(row.open)],[t('고가','High'),numeric(row.high)],[t('저가','Low'),numeric(row.low)],[t('거래량','Volume'),numeric(row.volume)]]:[[t('국가 후보 · 미검증','Country candidate · unverified'),row.country],[t('거래소 명칭','Exchange name'),row.exchange],[t('명부 확인일','Directory observed'),row.verifiedAt.slice(0,10)]];
    el('marketDetail').innerHTML='<h2 id="detailTitle">'+esc(row.ticker)+' · '+esc(row.name)+'</h2><dl>'+facts.map(function(x){return'<div><dt>'+esc(x[0])+'</dt><dd>'+esc(x[1])+'</dd></div>';}).join('')+'</dl><p>'+t('방법별 전망: 계산하지 않음. 검증된 과거 시세·기업행사·재무 입력이 부족합니다.','Method forecasts: not calculated. Validated history, corporate actions and financial inputs are missing.')+'</p><p>'+t('종목 유형(주식·ETF 등)은 별도 확인이 필요합니다.','Instrument type (stock, ETF, etc.) requires separate verification.')+'</p><a href="'+esc(daily?data.permission.evidenceUrl:row.sourceUrl)+'" target="_blank" rel="noopener noreferrer">'+t('원자료 출처 확인','View original source')+' ↗</a> <button type="button" id="closeMarketDetail" class="secondary">'+t('닫기','Close')+'</button>';
    el('marketDetail').hidden=false;el('marketDetail').focus();el('marketDetail').scrollIntoView({block:'start'});el('closeMarketDetail').addEventListener('click',function(){el('marketDetail').hidden=true;el('marketQuery').focus();});
    var url=new URL(location.href);url.searchParams.set('dataset',mode);url.searchParams.set('listing',row.listingId);history.replaceState(null,'',url);
  }
  function render(){
    var data=stores[mode];if(!data)return;var query=el('marketQuery').value.trim().toLocaleLowerCase(),country=el('marketCountry').value;
    rows=data.rows.filter(function(row){return(mode==='daily'||country==='ALL'||row.country===country)&&(!query||[row.ticker,row.name,row.exchange,row.mic,row.isin,row.figi].some(function(v){return v&&String(v).toLocaleLowerCase().includes(query);}));});
    page=Math.min(page,Math.max(0,Math.ceil(rows.length/size)-1));var shown=rows.slice(page*size,(page+1)*size),daily=mode==='daily';
    el('countryControl').hidden=daily;el('marketCaption').textContent=t(daily?'대만 거래소 일별 자료':'30개국 종목 발견 명부',daily?'Taiwan exchange daily snapshot':'30-country discovery directory');
    var heads=daily?[t('종목','Listing'),t('종가 (TWD)','Close (TWD)'),t('전일 대비','Change'),t('거래일','Trading date')]:[t('종목','Listing'),t('국가 후보','Country candidate'),t('거래소 후보','Exchange candidate'),t('분석','Analysis')];
    el('marketHead').innerHTML='<tr>'+heads.map(function(h){return'<th scope="col">'+esc(h)+'</th>';}).join('')+'</tr>';
    el('marketRows').innerHTML=shown.map(function(row,index){return'<tr><th scope="row"><button type="button" data-row="'+index+'">'+esc(row.ticker)+'</button><small>'+esc(row.name)+'</small></th>'+(daily?'<td>'+numeric(row.close)+'</td><td>'+numeric(row.change)+'</td><td>'+esc(row.asOf)+'</td>':'<td>'+esc(row.country)+'</td><td>'+esc(row.exchange)+'</td><td>'+t('자료 미연결','Not connected')+'</td>')+'</tr>';}).join('')||'<tr><td colspan="4">'+t('명부에서 찾지 못했습니다. 미수록 종목일 수 있으며 낮은 점수를 의미하지 않습니다.','Not found in this directory. It may be unlisted here; this is not a low score.')+'</td></tr>';
    el('marketRows').querySelectorAll('[data-row]').forEach(function(button){button.addEventListener('click',function(){detail(shown[Number(button.dataset.row)]);});});
    el('marketStatus').textContent=t('검색 결과 ','Results: ')+rows.length.toLocaleString()+t('개 / 수록 ',' / dataset ')+data.rows.length.toLocaleString()+t('개',' listings');el('marketPage').textContent=(page+1)+' / '+Math.max(1,Math.ceil(rows.length/size));el('marketPrev').disabled=page===0;el('marketNext').disabled=(page+1)*size>=rows.length;
    el('marketBoundary').textContent=daily?t('거래일 '+data.rows[0].asOf+'의 장 마감 후 자료입니다. 실시간이 아니며 조정주가·과거 이력·상승확률은 없습니다. ETF 등도 포함될 수 있습니다.','After-close snapshot for '+data.rows[0].asOf+'. Not live. No adjusted history or probability forecast. May include ETFs.'):t('명부 확인일 '+data.observedAt.slice(0,10)+'. 전체 상장종목을 망라하지 않습니다. 국가·종목명·상장 상태·통화·시장 식별자는 미검증이며 중복·과거 종목이 포함됩니다.','Directory observed '+data.observedAt.slice(0,10)+'. Not exhaustive. Countries, listing status, currency and market identifiers are unverified; duplicate and historical entries may be present.');
    el('marketSources').innerHTML=daily?'<p>'+esc(data.attribution)+'</p><p><a href="'+esc(data.permission.evidenceUrl)+'" target="_blank" rel="noopener noreferrer">Dataset</a> · <a href="'+esc(data.permission.licenseUrl)+'" target="_blank" rel="noopener noreferrer">Open Government Data License 1.0</a></p><p>'+t('수집 시각','Fetched at')+': '+esc(data.ingestedAt)+'</p>':'<p>Wikidata structured data · CC0 · <a href="'+esc(data.licenseUrl)+'" target="_blank" rel="noopener noreferrer">License</a></p><p>'+data.coverage.map(function(x){return esc(x.country)+': '+x.discovered;}).join(' · ')+'</p><p>'+t('각국 전체 상장 수를 검증하지 않아 커버리지 비율은 계산하지 않습니다.','Coverage percentages are unavailable because complete country denominators are not verified.')+'</p>';
  }
  async function load(){var current=++requestId;mode=el('marketMode').value;page=0;el('marketDetail').hidden=true;el('marketStatus').textContent=t('자료를 불러오는 중입니다.','Loading dataset…');el('marketRows').innerHTML='';try{if(!parity){var parityResponse=await fetch('./investing-parity-phase1.json');if(!parityResponse.ok)throw Error('PARITY_HTTP_'+parityResponse.status);parity=await parityResponse.json();renderParity();}if(!stores[mode]){var response=await fetch(mode==='daily'?'./twse-daily-fd1.json':'./global-directory-fd1.json');if(!response.ok)throw Error('HTTP '+response.status);var data=await response.json();if(data.encoding==='compact-listing/v1')data.rows=data.rows.map(function(r){return{listingId:r[0],ticker:r[1],name:r[2],country:r[3],exchange:r[4],sourceUrl:'https://www.wikidata.org/wiki/'+r[5],verifiedAt:data.observedAt};});if(!Array.isArray(data.rows)||!data.rows.length)throw Error('EMPTY_DATASET');if(current!==requestId)return;stores[mode]=data;if(mode==='directory')el('marketCountry').innerHTML='<option value="ALL">All countries</option>'+data.coverage.map(function(x){return'<option value="'+esc(x.country)+'">'+esc(x.country)+'</option>';}).join('');}if(current===requestId){render();var listing=new URL(location.href).searchParams.get('listing'),found=stores[mode].rows.find(function(x){return x.listingId===listing;});if(found)detail(found);}}catch(error){if(current===requestId){el('marketStatus').textContent=t('자료를 불러오지 못했습니다. 연결을 확인하고 검색 버튼으로 재시도하세요.','Dataset unavailable. Check your connection and press Search to retry.');el('marketBoundary').textContent=t('저장된 화면이 있어도 최신 시세가 있다는 뜻은 아닙니다.','An available page does not imply that current market data is available.');el('marketPrev').disabled=true;el('marketNext').disabled=true;}}}
  el('marketSearch').addEventListener('click',function(){page=0;stores[mode]?render():load();});el('marketQuery').addEventListener('keydown',function(e){if(e.key==='Enter'){page=0;stores[mode]?render():load();}});el('marketCountry').addEventListener('change',function(){page=0;render();});el('marketMode').addEventListener('change',load);el('marketPrev').addEventListener('click',function(){page--;render();});el('marketNext').addEventListener('click',function(){page++;render();});el('marketLocale').addEventListener('change',function(){labels();render();});
  var params=new URL(location.href).searchParams;el('marketLocale').value=params.get('lang')==='en'?'en':'ko';el('marketMode').value=params.get('dataset')==='directory'?'directory':'daily';el('marketQuery').value=params.get('q')||'';labels();load();
})();
