(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;else root.StockScannerPractice=api;})(typeof self!=='undefined'?self:this,function(){
  'use strict';
  var questions=[
    ['주가 100, 주당이익 5일 때 PER는?','Price 100, earnings per share 5: what is P/E?',['5','10','20','50'],2,'100 ÷ 5 = 20. 저평가 판단에는 업종·성장·위험도 비교가 필요합니다.','100 / 5 = 20. Valuation still requires peers, growth and risk.'],
    ['F-score의 9개 조건 중 7개를 충족했다면 점수는?','Seven of nine F-score criteria pass. What is the score?',['2','7','9','77'],1,'조건당 1점, 합계 7점입니다. 실제 계산에는 전기 비교와 정확한 정의가 필요합니다.','One point per criterion gives 7. Actual calculation requires prior-period comparisons and precise definitions.'],
    ['세후영업이익 30, 투하자본 200의 단순 ROIC는?','After-tax operating profit 30, invested capital 200: simplified ROIC?',['6%','15%','30%','200%'],1,'30 ÷ 200 × 100 = 15%. 금융업 등에는 다른 정의가 필요할 수 있습니다.','30 / 200 × 100 = 15%. Some industries require different definitions.'],
    ['예상 이익 100, 실제 이익 110의 예상 대비 초과율은?','Expected earnings 100, actual 110: earnings surprise?',['1%','10%','100%','110%'],1,'(110 − 100) ÷ 100 = 10%. 주가 상승 보장은 아닙니다.','(110 − 100) / 100 = 10%. It does not guarantee a price rise.'],
    ['관측 수익률 10%, 요인모형 설명분 8%의 잔여수익은?','Observed return 10%, factor-explained return 8%: residual?',['2%p','8%p','10%p','18%p'],0,'10 − 8 = 2%p. 양의 잔여수익 하나로 미래 성과를 증명할 수 없습니다.','10 − 8 = 2 percentage points. One residual does not establish future performance.'],
    ['12개월 전 조정가격 100, 1개월 전 120의 12-1 수익률은?','Adjusted price 100 twelve months ago, 120 one month ago: 12-1 return?',['12%','16.7%','20%','120%'],2,'120 ÷ 100 − 1 = 20%. 최근 한 달은 제외했고 비교 기준이 필요합니다.','120 / 100 − 1 = 20%. The latest month is excluded; benchmark comparison remains necessary.'],
    ['단기 이동평균 120, 장기 100이 알려주는 것은?','Short moving average 120, long average 100: what does this indicate?',['상승 보장 / Guaranteed rise','상향 추세 신호 / Upward trend signal','수익률 120% / 120% return','자료 없음 / No data'],1,'단기가 장기보다 높다는 추세 신호입니다. 횡보장에서는 잘못된 신호가 생길 수 있습니다.','The short average is above the long average. Sideways markets can produce false signals.'],
    ['RSI 20이면 내일 반드시 반등하는가?','Does RSI 20 guarantee a rebound tomorrow?',['예 / Yes','아니요 / No','20% 보장 / 20% guaranteed','원금 보장 / Capital guaranteed'],1,'과매도 지표만으로 반등을 보장하지 않습니다. 구조적 악화를 먼저 확인합니다.','Oversold readings do not guarantee a rebound. Check structural deterioration.'],
    ['동일 기간 변동성 A=10%, B=25%. 더 낮은 변동성은?','Same-period volatility: A=10%, B=25%. Which is lower?',['A','B','동일 / Same','수익률만 비교 / Compare return only'],0,'A의 변동성이 낮지만 손실이 없다는 뜻은 아닙니다. 관찰 기간과 측정 단위가 같아야 비교할 수 있습니다.','A has lower volatility, but it can still lose value.'],
    ['자사주 매입 발표 100, 실제 집행 20. 집행률은?','Buyback announced 100, executed 20. Execution rate?',['5%','20%','80%','100%'],1,'20 ÷ 100 = 20%. 발표와 집행은 서로 다릅니다.','20 / 100 = 20%. Announcement and execution are different.'],
    ['순이익 100, 영업현금흐름 60. 단순 발생액 차이는?','Net income 100, operating cash flow 60. Simplified accrual difference?',['40','60','100','160'],0,'100 − 60 = 40. 비교하려면 규모·회계기준·업종을 통제해야 합니다.','100 − 60 = 40. Comparisons need size, accounting and industry controls.'],
    ['가치 계열 20, 품질 계열의 두 방법 40·60. 계열 균등 평균은?','Value family 20; two quality methods 40 and 60. Equal family mean?',['30','35','40','50'],1,'품질 계열 (40+60)/2=50, 계열 평균 (20+50)/2=35.','Quality family: (40+60)/2=50. Family mean: (20+50)/2=35.'],
    ['합성점수 80은 상승확률 80%인가?','Does synthetic score 80 mean an 80% rise probability?',['예 / Yes','아니요 / No','항상 / Always','손실 0 / Zero loss'],1,'점수와 보정된 확률은 다릅니다. 확률에는 별도 실증 검증이 필요합니다.','Scores and calibrated probabilities differ. Probabilities require separate empirical validation.'],
    ['8월 1일 보고서에 8월 5일 발표 재무를 써도 되는가?','Can an August 1 report use financials published August 5?',['예 / Yes','아니요 / No','주가가 오르면 / If price rises','무료이면 / If free'],1,'미래정보가 섞입니다. 당시 이용 가능했던 정보만 써야 합니다.','That leaks future information. Only information available at the time is valid.'],
    ['필수 입력이 빠졌을 때 올바른 동작은?','A required input is missing. Correct action?',['임의 점수 / Invent score','0으로 대체 / Replace with zero','계산 보류 / Withhold calculation','다른 종목 복사 / Copy another'],2,'빠진 필드와 이유를 밝히고 계산을 보류합니다. 임의의 숫자나 0으로 대체하지 않습니다.','Withhold calculation and identify the missing input.'],
    ['어제 종가의 올바른 표시는?','How should yesterday’s closing price be labeled?',['실시간 / Live','기준 거래일 표시 / Show trading date','오늘 시세 / Today price','예상 종가 / Forecast close'],1,'원천 거래일·지연을 표시해야 현재 가격과 혼동하지 않습니다.','Show the original trading date and delay to avoid confusion with current prices.'],
    ['명부에서 찾은 기업을 바로 합성점수와 연결해도 되는가?','Can a discovered company be assigned a synthetic score as a real forecast?',['예 / Yes','아니요 / No','이름이 같으면 / If names match','국가가 같으면 / If countries match'],1,'발견·실자료·분석은 별도 상태입니다. 확인된 식별자와 입력이 필요합니다.','Discovery, real data and analysis are separate states. Verified identifiers and inputs are required.'],
    ['두 출처의 통화·날짜가 다를 때 먼저 할 일은?','Two sources have different currencies and dates. First action?',['평균 / Average them','높은 값 선택 / Pick higher','정의·시점 대조 / Reconcile definitions and time','낮은 값 삭제 / Delete lower'],2,'정의·통화·시점을 확인하고 불일치가 해소될 때까지 판정을 보류합니다.','Reconcile definition, currency and time, and withhold judgment until resolved.']
  ];
  function get(index,english){var q=questions[index];if(!q)throw Error('PRACTICE_NOT_FOUND');return{id:'practice-'+index,title:q[english?1:0],choices:q[2].slice(),explanation:q[english?5:4]};}
  function answer(index,choice){var q=questions[index];if(!q||!Number.isInteger(choice)||choice<0||choice>3)throw Error('PRACTICE_ANSWER_INVALID');return{correct:choice===q[3],choice:choice};}
  return{count:questions.length,get:get,answer:answer};
});
