(function(root,factory){var api=factory();if(typeof module==='object'&&module.exports)module.exports=api;if(root)root.KabuResearch=api;})(typeof globalThis!=='undefined'?globalThis:null,function(){
  'use strict';
  var FIXTURES=[
    {code:'7203',name:'토요타자동차',sector:'자동차',evidence:'고정 시험자료'},
    {code:'6758',name:'소니그룹',sector:'전자',evidence:'고정 시험자료'},
    {code:'9984',name:'소프트뱅크그룹',sector:'통신',evidence:'고정 시험자료'},
    {code:'9432',name:'NTT',sector:'통신',evidence:'고정 시험자료'},
    {code:'8306',name:'미쓰비시UFJ',sector:'금융',evidence:'고정 시험자료'}
  ];
  var catalog=FIXTURES.slice();
  function setCatalog(rows){if(!Array.isArray(rows)||rows.length!==10000)return {changed:false,error:'CATALOG_COUNT_INVALID'};var seen=new Set();for(var i=0;i<rows.length;i++){var row=rows[i];if(!row||row.fixture!==true||!/^[A-Z0-9]{5}$/.test(String(row.code||''))||seen.has(row.code)||!row.name||!row.sector||!row.evidence)return {changed:false,error:'CATALOG_ROW_INVALID'};seen.add(row.code);}catalog=rows.slice();return {changed:true,count:catalog.length};}
  function rows(){return catalog;}
  function statusOf(){return 'HOLD';}
  function filterRows(rows,value){value=value||{};var q=String(value.query||'').trim().toLowerCase(),sort=['code','name','sector'].indexOf(value.sort)>=0?value.sort:'code',direction=value.direction==='desc'?-1:1;return (rows||[]).filter(function(row){var matches=!q||[row.code,row.name,row.sector].some(function(field){return String(field).toLowerCase().indexOf(q)>=0;});return matches&&(!value.holdOnly||statusOf(row)==='HOLD');}).slice().sort(function(a,b){return String(a[sort]).localeCompare(String(b[sort]),'ko')*direction;});}
  function toggleCompare(codes,code){var next=Array.isArray(codes)?codes.slice(0,4):[],index=next.indexOf(code);if(index>=0){next.splice(index,1);return {codes:next,changed:true};}if(next.length>=4)return {codes:next,changed:false,error:'COMPARE_LIMIT'};next.push(code);return {codes:next,changed:true};}
  function savedSearch(value,now){value=value||{};var name=String(value.name||'').trim().slice(0,40);if(!name)return null;return {id:'search:'+String(now||Date.now()),name:name,query:String(value.query||'').trim().slice(0,40),sort:['code','name','sector'].indexOf(value.sort)>=0?value.sort:'code',direction:value.direction==='desc'?'desc':'asc',createdAt:new Date(now||Date.now()).toISOString()};}
  function detail(code,state){var row=catalog.find(function(item){return item.code===code;})||FIXTURES.find(function(item){return item.code===code;});if(!row)return null;return {code:row.code,name:row.name,sector:row.sector,status:statusOf(row),sourceTitle:row.evidence,sourceAnchor:'fixture:'+row.code,sourceUrl:null,calculation:'실자료 검토 전 · 계산하지 않음',memo:String((state&&state.researchNotes&&state.researchNotes[row.code])||'').slice(0,500),decisionHistory:[{status:'HOLD',reason:'합성 시험자료이며 실제 원문 검토 전',sourceAnchor:'fixture:'+row.code}]};}
  function exportRows(state){state=state||{};var output=[];function add(type,value,note,code){var item=code?detail(code,state):null;output.push({type:type,value:String(value),note:String(note||''),sourceAnchor:item?item.sourceAnchor:'',status:item?item.status:''});}(state.watchlist||[]).forEach(function(code){add('watchlist',code,'',code);});(state.positions||[]).forEach(function(item){add('position',item.code,item.memo,item.code);});(state.savedSearches||[]).forEach(function(item){add('saved-search',item.name,[item.query||'전체',item.sort||'code',item.direction||'asc'].join(' / '));});(state.compareCodes||[]).forEach(function(code){add('comparison',code,(state.researchNotes||{})[code]||'',code);});if(state.selectedResearchCode&&!(state.compareCodes||[]).includes(state.selectedResearchCode))add('selected-research',state.selectedResearchCode,(state.researchNotes||{})[state.selectedResearchCode]||'',state.selectedResearchCode);return output.slice(0,10000);}
  function safeCell(value){var text=String(value==null?'':value);if(/^[=+\-@]/.test(text))text="'"+text;return '"'+text.replace(/"/g,'""')+'"';}
  function toCsv(rows){var lines=[['type','value','note','sourceAnchor','status'].map(safeCell).join(',')];(rows||[]).slice(0,10000).forEach(function(row){lines.push([row.type,row.value,row.note,row.sourceAnchor,row.status].map(safeCell).join(','));});return '\uFEFF'+lines.join('\r\n')+'\r\n';}
  function buildBundle(state,version,now){var selected=state&&state.selectedResearchCode?detail(state.selectedResearchCode,state):null,compared=(state&&state.compareCodes||[]).map(function(code){return detail(code,state);}).filter(Boolean);return {schema:'kabulens-research-bundle/v1',appVersion:String(version||''),exportedAt:new Date(now||Date.now()).toISOString(),boundary:'SYNTHETIC_FIXED_NOT_REAL_COMPANY',userData:state,evidence:{selected:selected,compared:compared}};}
  return {FIXTURES:FIXTURES,setCatalog:setCatalog,rows:rows,statusOf:statusOf,detail:detail,filterRows:filterRows,toggleCompare:toggleCompare,savedSearch:savedSearch,exportRows:exportRows,toCsv:toCsv,buildBundle:buildBundle};
});
